version: '3'

services:
  app:
    container_name: "app"
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - rabbit_mq

  preprocess:
    container_name: "preprocess"
    build:
      dockerfile: Dockerfile.preprocess
    environment:
      PYTHONUNBUFFERED: '1'
    restart: always
    depends_on:
      - rabbit_mq
      - app

  postprocess:
    container_name: "postprocess"
    build:
      dockerfile: Dockerfile.postprocess
    environment:
      PYTHONUNBUFFERED: '1'
    restart: always
    depends_on:
      - whisper

  rabbit_mq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=bot
      - RABBITMQ_DEFAULT_PASS=bot
      - heartbeat = 3600
    container_name: "rabbit_mq"
    ports:
      - 5672:5672
      - 15672:15672

  bot:
    container_name: "bot"
    build:
      dockerfile: Dockerfile.bot
    depends_on:
      - rabbit_mq
      - app
      - minio

  minio:
    container_name: "minio"
    image: quay.io/minio/minio:latest
    hostname: minio
    command: minio server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio:/var/lib/minio

  whisper:
    container_name: "whisper"
    build:
      dockerfile: Dockerfile.whisper
    ports:
      - 9091:9090
    environment:
      PYTHONUNBUFFERED: '1'
    restart: always
    depends_on:
      - preprocess
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  redis:
    container_name: "redis"
    image: redis/redis-stack
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis

  couchdb:
    container_name: "couchdb"
    build:
      dockerfile: Dockerfile.couchdb
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER =admin
      - COUCHDB_PASSWORD = password
      - NODENAME = transcripts
    volumes:
      - couchdb:/opt/couchdb/data

volumes:
  minio:
    driver: local
  couchdb:
    driver: local
  redis:
    driver: local
