version: '3'

services:
 app:
  container_name: "app"
  build:
    dockerfile: Dockerfile
  ports:
    - 8000:8000
  restart: always
  depends_on:
    - rabbit_mq

 preprocess:
  container_name: "preprocess"
  build:
    dockerfile: Dockerfile.preprocess
  environment:
    PYTHONUNBUFFERED: '1'
  restart: always
  depends_on:
    - rabbit_mq
    - app

 process:
  container_name: "process"
  build:
    dockerfile: Dockerfile.process
  environment:
    PYTHONUNBUFFERED: '1'
  restart: always
  depends_on:
    - preprocess

 postprocess:
  container_name: "postprocess"
  build:
    dockerfile: Dockerfile.postprocess
  environment:
    PYTHONUNBUFFERED: '1'
  restart: always
  depends_on:
    - process

 rabbit_mq:
  image: rabbitmq:3.12-management
  hostname: rabbitmq
  restart: always
  environment:
    - RABBITMQ_DEFAULT_USER=bot
    - RABBITMQ_DEFAULT_PASS=bot
  container_name: "rabbit_mq"
  ports:
    - 5672:5672
    - 15672:15672
 bot:
   container_name: "bot"
   build:
    dockerfile: Dockerfile.bot
   depends_on:
    - rabbit_mq
    - app
